services:
  db:
    image: postgres:15-alpine
    container_name: egrex-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-CAMILO129}
      POSTGRES_DB: ${POSTGRES_DB:-bienestar}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - egrex-network

  backend:
    build: ../egrex-backend
    container_name: egrex-backend
    restart: always
    environment:
      - PORT=8080
      - NODE_ENV=production
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${POSTGRES_USER:-postgres}
      - DB_PASSWORD=${POSTGRES_PASSWORD:-CAMILO129}
      - DB_NAME=${POSTGRES_DB:-bienestar}
      - JWT_SECRET=${JWT_SECRET:-clave_super_secreta_123}
    depends_on:
      - db
    networks:
      - egrex-network

  frontend:
    build: .
    container_name: egrex-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - egrex-network

volumes:
  pgdata:


networks:
  egrex-network:
    driver: bridge
