services:
  db:
    image: postgres:15-alpine
    container_name: egrex-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: CAMILO129
      POSTGRES_DB: bienestar
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ../egrex-backend
    container_name: egrex-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - NODE_ENV=development
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=CAMILO129
      - DB_NAME=bienestar
      - JWT_SECRET=clave_super_secreta_123
    depends_on:
      - db

  frontend:
    build: .
    container_name: egrex-frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  pgdata:
