services:
  frontend:
    build: .
    container_name: egrex-frontend
    restart: always
    ports:
      - "80:80"
    networks:
      - egrex-network

networks:
  egrex-network:
    external: true
